### ISSUE TITLE
Look into moving from rustc-serialize to serde

### ISSUE THREAD

**Issue by TheZoq2** [TheZoq2/flash#10]

**Comment by dtolnay** [comment]
The rustc-serialize crate has been deprecated ([announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay)) so this would be a good time to make the move. Is there any functionality you would require from another library before this would be possible?

**Comment by TheZoq2** [comment]
@dtolnay Nope, as far as I know, it should be a fairly simple change. I just haven't got around to doing it yet
